# Generated by Django 4.2.2 on 2023-08-10 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.CharField(max_length=60)),
                ("addip", models.CharField(max_length=40)),
                ("client_secret", models.CharField(max_length=80)),
                ("client_id", models.CharField(max_length=80)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyAuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.CharField(max_length=20)),
                ("access_token", models.CharField(max_length=300)),
                ("refresh_token", models.CharField(max_length=300, null=True)),
                ("username", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MyServerMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ServerJoins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.CharField(max_length=80)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("has_joined", models.BooleanField(default=False)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.discordserver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("duration", models.IntegerField()),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscordUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.CharField(max_length=40, null=True, unique=True)),
                ("access_token", models.CharField(max_length=300)),
                ("refresh_token", models.CharField(max_length=300, null=True)),
                ("username", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=150, null=True)),
                (
                    "server_guild",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.discordserver",
                    ),
                ),
            ],
        ),
    ]
