# Generated by Django 4.2.2 on 2023-07-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordUsers",
            fields=[
                (
                    "userID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("access_token", models.CharField(max_length=300)),
                ("username", models.CharField(max_length=50)),
            ],
        ),
    ]
