# Generated by Django 4.2.2 on 2023-07-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordusers",
            name="linked_bot_public",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
