# Generated by Django 4.2.2 on 2023-08-17 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordserver",
            name="color",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="discordserver",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="discordserver",
            name="webhook_url",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="discordserver",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.discordusers"
            ),
        ),
    ]
