# Generated by Django 4.2.2 on 2023-07-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_discordusers_linked_bot_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordusers",
            name="refresh_token",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
