# Generated by Django 4.2.2 on 2023-08-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_alter_discordserver_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordserver",
            name="owner_discord_id",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
