# Generated by Django 4.2.2 on 2023-08-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_discordserver_owner_discord_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordserver",
            name="token",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
