# Generated by Django 4.2.2 on 2023-08-27 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_discordserver_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('footer', models.CharField(blank=True, max_length=50, null=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.discordserver')),
            ],
        ),
        migrations.DeleteModel(
            name='MyServerMembers',
        ),
        migrations.AlterField(
            model_name='discordusers',
            name='server_guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.discordserver'),
        ),
    ]
