# Generated by Django 4.2.2 on 2023-08-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_button_image_rename_discordserver_bots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserverjoined',
            name='roleToGive',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
