# Generated by Django 4.2.2 on 2023-09-02 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_discordserverjoined_roletogive'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.bots'),
        ),
    ]
