# Generated by Django 4.2.2 on 2023-09-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_payment_is_over_alter_payment_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.bots'),
        ),
    ]
